version: '3.8'

services:
    front-end:
        build:
            context: todo_frontend
            dockerfile: Dockerfile
        ports:
            - 80:3000
        depends_on:
            - back-end
    back-end:
        build:
            context: ToDo
            dockerfile: Dockerfile
        ports:
            - 8080:8080
        environment:
            DB_URL: jdbc:mysql://db/opos
            DB_USERNAME: ivana
            DB_PASSWORD: ivana1
        depends_on:
            - db
    db:
        image: mysql:8.0.33
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            MYSQL_DATABASE: opos
            MYSQL_ROOT_PASSWORD: ivana1
            MYSQL_USER: ivana
            MYSQL_PASSWORD: ivana1

volumes:
  dbdata: